$(".logo_header").addClass("funciono perra");
$('.owl-carousel').owlCarousel({
    loop:true,
    margin:0,
    dots:true,
    autoplay:true,
    //autoplayHoverPause:true,
    autoplayTimeout:5000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})